language: python
python:
    - "3.7"
install:
    - pip install -r requirements.txt
    - pip list

script:
    # your test script goes here
    - coverage run --omit=\*/test_\* -m unittest
    - codecov

  # Use Sphinx to make the html docs
    - export PYTHONPATH=$PYTHONPATH:$PWD
    - echo $PYTHONPATH
    - cd docs
    - make html
  # Tell GitHub not to use jekyll to compile the docs
    - touch build/html/.nojekyll

# Tell Travis CI to copy the documentation to the gh-pages branch of
# your GitHub repository.
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  local_dir: build/html/