name: Sphinx

on:
  workflow_call:

jobs:
  sphinx:
    runs-on: ubuntu-latest
    # if: ${{ github.event_name != 'pull_request' }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev,docs]
        pip install git+https://github.com/petercorke/sphinx-autorun.git
        pip install sympy
        sudo apt-get install graphviz
    # - name: Build docs
    #   run: |
    #     cd docs
    #     make html
    #     # Tell GitHub not to use jekyll to compile the docs
    #     touch build/html/.nojekyll
    #     cd ../
    # - name: Commit documentation changes
    #   run: |
    #     git clone https://github.com/petercorke/spatialmath-python.git --branch gh-pages --single-branch gh-pages
    #     cp -r docs/build/html/* gh-pages/
    #     cd gh-pages
    #     git config --local user.email "action@github.com"
    #     git config --local user.name "GitHub Action"
    #     git add .
    #     git commit -m "Update documentation" -a || true
    #     # The above command will fail if no changes were present, so we ignore
    #     # that.
    # - name: Push changes
    #   uses: ad-m/github-push-action@master
    #   with:
    #     branch: gh-pages
    #     directory: gh-pages
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
